### PR TITLE
Add AnyScheduler

### PR DESCRIPTION
**Pull request by ddddxxx**
Add type erased `Scheduler` so one can inject a scheduler to non-generic classes.

As requested here: https://forums.swift.org/t/is-there-an-easy-way-to-inject-a-combine-scheduler/35756

### CODE REVIEW

**Review by luoxiu — APPROVED** [review]

**Comment by inamiy** [comment]
Hi, I came across with this nice impl which I want to use in my codebase!

Do you think you can split this as a standalone library?
Or can I copy to make a standalone repo for this? 
(I want to use in multiple projects so copy-pasting to each proj is not a desired solution)

**Comment by ddddxxx** [comment]
@inamiy Hi, I'm glad it was helpful to you. Can you just use CXExtensions as a whole? I believe it's small and focus enough, and I don't feel like making it any smaller.

Anyway, this project is available under MIT License, you can always copy-pasting or making a standalone repo as you like.

**Comment by inamiy** [comment]
@ddddxxx 
Thanks! Since `CXExtensions` depends on `CombineX` which is a bit too much for my current use case,
I migrated `AnyScheduler` code to the following repository:

https://github.com/inamiy/AnyScheduler/pull/1

I added your name as a credit, and if you find it nicer to maintain by yourself, please let me know.
I can either add a write access or transfer to your organization.

**Comment by ddddxxx** [comment]
@inamiy Actually CXExtensions depends on `CXShim`, not `CombineX`. It works perfectly fine with system Combine. I also wrote a [article](https://forums.swift.org/t/combine-backward-deployment-and-linux/37855) about it.

Basically you can use CXExtensions without knowing CombineX at all. No extra set up, no extra dependency, no extra runtime cost. The only difference is that you check out the CombineX repo when resolving package (but it doesn't get bundled into the binary). If you really don't like the check out, you're welcome to maintain your micro-framework :)

**Comment by inamiy** [comment]
> Actually CXExtensions depends on CXShim, not CombineX

Ah I got it! Thanks for sharing the article too. 
I wasn't aware of the multiple environment support you've done.

From the user's perspective though, regardless of how system builds binary efficiently, I think having a simpler repo structure would be easier to figure out about the library, so I will keep mine for at least my own use cases.
Hope I can keep tracking your updates 😄

**Pull request merged**
